export enum channel {
    // For Private user
    JOIN_PRIVATE_USER_CHANNEL = "JOIN_PRIVATE_USER_CHANNEL",
    
    // For User
    JOIN_PRIVATE_WALLET_USER_CHANNEL = "JOIN_PRIVATE_WALLET_USER_CHANNEL",


    // For Private admin
    JOIN_PRIVATE_ADMIN_CHANNEL = "JOIN_PRIVATE_ADMIN_CHANNEL",    

    // For Admin
    JOIN_PRIVATE_ADMIN_REPORT_REGISTER = "JOIN_PRIVATE_ADMIN_REPORT_REGISTER",
    JOIN_PRIVATE_ADMIN_REPORT_LOGIN = "JOIN_PRIVATE_ADMIN_REPORT_LOGIN",
    JOIN_PRIVATE_ADMIN_REPORT_OTP = "JOIN_PRIVATE_ADMIN_REPORT_OTP"
}