export enum channel {
    JOIN_PRIVATE_USER_CHANNEL = "JOIN_PRIVATE_USER_CHANNEL",
    JOIN_PRIVATE_OTP_SYSTEM = "JOIN_PRIVATE_OTP_SYSTEM",
    JOIN_PRIVATE_WALLET_USER_CHANNEL = "JOIN_PRIVATE_WALLET_USER_CHANNEL",
}